### ISSUE TITLE
Only gets a black screen with paddle/time - no data being shown

### ISSUE THREAD

**Issue by fredriksvantes** [fcsonline/nodestalgia#19]
I believe I've found a bug:
When installed with npm, the executable will be located in: ~/local/lib/node_modules/nodestalgia/bin/nodestalgia
This causes the application to break when it starts:
$ nodestalgia /var/log/DAM/httpd/*/access.log
path.existsSync is now called `fs.existsSync`.
module.js:340
throw err;
^
Error: Cannot find module './routes/index'
at Function.Module._resolveFilename (module.js:338:15)
at Function.Module._load (module.js:280:25)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at /www/fredrik/home/fredrik/local/lib/node_modules/nodestalgia/bin/nodestalgia:63:20
at Array.map (native)
at Object.<anonymous> (/www/fredrik/home/fredrik/local/lib/node_modules/nodestalgia/bin/nodestalgia:59:6)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
The reason for this is that the nodestalgia executable is located in the "bin" directory, so it tries to find "routes/index.js" at ~/local/lib/node_modules/nodestalgia/bin/routes/index.js
If you move the executable to ~/local/lib/node_modules/nodestalgia/nodestalgia then it starts perfectly fine.
I haveis an issue though.
Even though the app starts correctly and starts showing this in the stdout, it doesn't work when browsing to the site:
debug - served static content /socket.io.js
DNS: 88.129.221.52 resolved to h88-129-221-52.dynamic.se.alltele.net
DNS: 80.170.64.166 resolved to m80-170-64-166.cust.tele2.se
DNS: 62.198.97.57 resolved to 0x3ec66139.inet.dsl.telianet.dk
When I browse to the site, all I get is a black background, date and time (which updates), the red paddle as well as the status down in the top right corner (which doesn't update itself). I don't have any balls flying towards the 
Do you have any idea what could be causing this..?
I'm running the following:
$ node -v
v0.10.5
$ npm -v
1.2.18
$ nodestalgia -V
0.1.1

**Comment by fcsonline** [comment]
I have fixed the issue! fde7ccf9207f564649e3c9294a42a8816b25ea12

I deployed the version 1.1.2.

Thanks for report it!
